version: "3"
services:
  golang_app:
    build: ./assigment-2
    container_name: golang_app
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "8080:80"
      - "9001:9001"
    depends_on:
      - golang_app
